<?php
/**
 * User: wangting
 * Date: 12-11-28
 * Time: 下午1:53
 * copyright 2012 tiddr.de
 */
?>
<div class="row-fluid">
    <div class="span4">
        <img src="/person_images/<?php echo $this->person->getImagePath(); ?>"/>
    </div>
    <div class="span8">
        <?php echo $this->person->getName(); ?>
        <div class="description">
            <?php echo $this->person->getDescription();?>
        </div>
    </div>
</div>
<h2> Products of <?php echo $this->person->getName(); ?></h2>
<?php
echo $this->partial('partial/productlist', array(
    'products' => $this->products, 'imageMapper' => $this->imageMapper,
    'personMapper' => $this->personMapper,
));
?>
