<div  class="row-fluid product-list">
    <h3 class="title"><a href="#">2013年8月 Aug 2013</a></h3>
    <ul>
<?php foreach ($this->products as $product): ?>
        <li>
            <div class="photo">
                <a href="<?php echo $this->url('product-front', array('action' => 'index', 'id' => $product->getId())); ?>">
                    <?php
                    $imagePath = $this->imageMapper->getFirstImage($product->getId())->readListProductImage();
                    if ($imagePath) {
                        echo '<img src="' . $imagePath . '"  width="300" height="300"/>';
                    } else {
                        echo '<img src="/product-images/dummy.jpg"  width="300" height="300"/>';
                    }
                    ?>
                </a>
            </div>
            <div class="desc">
                <?php echo $product->getDisplayName(); ?>
            </div>
        </li>
<?php endforeach; ?>
    </ul>
</div>

<!--            Author: <a href="--><?php //echo $this->url('person-front', array('action' => 'index', 'id' => $product->getAuthorId())); ?><!--">-->
<!--            --><?php //echo $this->personMapper->findById($product->getAuthorId())->getName();?>
<!--            </a>-->
