<?php
/**
 * User: wangting
 * Date: 12-11-28
 * Time: 下午3:05
 * copyright 2012 tiddr.de
 */
?>
<div  class="row-fluid product-list">
    <?php $index = 0; ?>
<?php foreach ($this->products as $product): ?>

    <?php if ($index % 4 == 0) : ?>
        </div>
        <div  class="row-fluid product-list">
        <?php endif; ?>
    <?php $index++; ?>
    <div class="single-product span3">
        <div class="category-image">
            <a href="<?php echo $this->url('product-front', array('action' => 'index', 'id' => $product->getId())); ?>">
                <?php
                $imagePath = $this->imageMapper->getFirstImage($product->getId())->readListProductImage();
                if ($imagePath) {
                    echo '<img src="' . $imagePath . '"  width="300" height="300"/>';
                } else {
                    echo '<img src="/product-images/dummy.jpg"  width="300" height="300"/>';
                }
                ?>
            </a>
            Author: <a href="<?php echo $this->url('person-front', array('action' => 'index', 'id' => $product->getAuthorId())); ?>">
            <?php echo $this->personMapper->findById($product->getAuthorId())->getName();?>
            </a>
        </div>
        <div class="product-description">
            <?php echo $product->getDisplayName(); ?>
        </div>
    </div>
    <?php endforeach; ?>

