<?php
$title = 'Edit Product';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$images = $this->images;
$form = $this->form;
$form->setAttribute('action', $this->url('product', array('action' => 'edit', 'id' => $this->id)));
$form->prepare();
echo $this->formTwb($form);

//echo $this->form()->openTag($form);
//echo $this->formHidden($form->get('id'));
//echo $this->formRow($form->get('name'));
//echo $this->formRow($form->get('category_id'));
//echo $this->formRow($form->get('display_name'));
//echo $this->formRow($form->get('price'));
//echo $this->formRow($form->get('description'));
//echo $this->formRow($form->get('submit'));
//echo $this->form()->closeTag();

?>
<h2> Add new Image </h2>
<a class="btn" href="<?php echo $this->url('product-image', array('action' => 'add', 'id' => $this->id)); ?>">Add </a>
<h2>Edit images</h2>
<ul>
    <?php foreach($images as $image) :?>
    <li><img src="<?php echo $image->readThumbImagePath(); ?>"/>
        <a class="btn" href="<?php echo $this->url('product-image', array('action' => 'edit', 'id' => $image->getId())); ?>">edit</a>
    </li>
    <?php endforeach; ?>
</ul>
<script>
$(function() {
    $( "#created_at" ).datepicker({ dateFormat: "yy-mm-dd" });
});
</script>

