<?php
$title = 'Edit Product';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('product', array('action' => 'edit', 'id' => $this->id)));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('category_id'));
echo $this->formRow($form->get('display_name'));
echo $this->formRow($form->get('price'));
echo $this->formRow($form->get('description'));
echo $this->formRow($form->get('image1'));
echo $this->formRow($form->get('image2'));
echo $this->formRow($form->get('submit'));
echo $this->form()->closeTag();