<?php
$title = 'Product';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a class="btn" href="<?php echo $this->url('product', array('action' => 'add')); ?>">Add</a>
</p>
<table class="table table-striped">
    <tr>
        <th><?php echo $this->translate('Product id'); ?></th>
        <th><?php echo $this->translate('Sub Category'); ?></th>
        <th><?php echo $this->translate('Name'); ?></th>
        <th><?php echo $this->translate('Display name'); ?></th>
        <th><?php echo $this->translate('Price'); ?></th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($products as $product) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($product->getId()); ?></td>
            <td><?php echo $this->escapeHtml($product->readSubCategoryName()); ?></td>
            <td><?php echo $this->escapeHtml($product->getName()); ?></td>
            <td><?php echo $this->escapeHtml($product->getDisplayName()); ?></td>
            <td><?php echo $this->escapeHtml($product->getPrice()); ?></td>
            <td>
                <a class="btn" href="<?php echo $this->url(
        'product', array('action' => 'edit', 'id' => $product->getId()));
        ?>"> <?php echo $this->translate('Edit'); ?> </a>
                <a class="btn" href="<?php echo $this->url(
                   'product', array('action' => 'delete', 'id' => $product->getId()));
               ?>"> <?php echo $this->translate('Delete', 'todo'); ?></a>
            </td>

        </tr>
<?php endforeach; ?>
</table>
    <?php echo $this->paginationControl($products, 'Sliding', 'pagination_control', array('route' => 'product-list'));
