<?php
$product = $this->product;
$images = $this->images;
?>

<h3><?php echo $product->getName(); ?></h3>
<?php foreach ($images as $image): ?>
<div class="single-product-image">
    <img src="<?php echo $image->readSingleProductImage(); ?>" width="300" height="300" />
</div>

<?php endforeach ?>
<div  class="row-fluid">
    <div class="product-description-left span6">
        <?php echo $product->getDescription(); ?>
    </div>
    <div class="product-description-right span6">
         <?php echo $product->getDescription(); ?>
    </div>
</div>

</dl>