<?php
$product = $this->product;
$images = $this->images;
$country = $this->country;
?>
<div class="text-info">
    <h1><?php echo $product->getName(); ?></h1>
    <dl>
        <dt>产地</dt>
        <dd>
            <a href="<?php echo $this->url('product-front-filter', array('filter-name' => 'country', 'filter-value'=> $country));?>" >
                <?php echo $country;?>
            </a>
        </dd>
        <dt>主要材质</dt>
        <dd>
            <a href="<?php echo $this->url('product-front-filter', array('filter-name' => 'material', 'filter-value'=> $product->getMaterial()));?>" >
            <?php echo $product->getMaterial(); ?>
            </a>
        </dd>
        <dt>创作者</dt>
        <dd>
           <a href="<?php echo $this->url('person-front', array('action' => 'index', 'id' => $this->author->getId()));?>">
             <?php echo $this->author->getName(); ?>
           </a>
        </dd>
        <dt>风格系列</dt>
        <dd><?php echo $product->getStyle(); ?></dd>
    </dl>
    <h3>相关参数</h3>
    <p><?php echo $product->getParameters(); ?></p>
    <h3>美物介绍</h3>
    <p><?php echo $product->getDescription(); ?></p>

    <div class="opt-groups">
        <span class="price">￥<?php echo $product->getPrice();?></span>
        <a href="#" class="buy-lnk">购买链接</a>
    </div>
    <div class="share-links">
        <!-- Baidu Button BEGIN -->
        <div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">
            <a class="bds_qzone"></a>
            <a class="bds_tsina"></a>
            <a class="bds_tqq"></a>
            <a class="bds_renren"></a>
            <a class="bds_t163"></a>
            <span class="bds_more"></span>
        </div>
        <script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=0" ></script>
        <script type="text/javascript" id="bdshell_js"></script>
        <script type="text/javascript">
            document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + Math.ceil(new Date()/3600000)
        </script>
        <!-- Baidu Button END -->
    </div>
</div>
<div class="product-images">
    <div class="pre-image">
        <img src="/images/slide_big_image.png" alt="">
    </div>
    <div class="image-listing">
        <ul>
            <li>
                <img src="/images/slide_small_image.png" alt="">
            </li>
            <li>
                <img src="/images/slide_small_image.png" alt="">
            </li>
            <li>
                <img src="/images/slide_small_image.png" alt="">
            </li>
            <li>
                <img src="/images/slide_small_image.png" alt="">
            </li>
        </ul>
    </div>
</div>

