<?php
$images = $this->images;
$first = true;
?>

<div class="container-fluid bigger-top-margin">
    <div class="row-fluid">

        <div class="span2">
            <h2>卿作</h2>
            Tsingzoo
            <ul class="nav nav-pills nav-stacked">
                <li><a href="#">头饰</a></li>
                <li><a href="#">项链</a></li>
                <li><a href="#">戒指</a></li>
                <li><a href="#">关于我们</a></li>
                <li><a href="#">联系方式</a></li>
            </ul>
            <!--Sidebar content-->
        </div>
        <div class="span10">
            <!-- slide {{{ -->
            <div class="row-fluid">
                <div id="pro-slide" class="carousel slide">
                    <div class="carousel-inner">
                        <?php foreach ($images as $image) : ?>
                            <div class="<?php echo $first ? 'active' : ''; ?> item">
                                <img alt="some picture here" src="<?php echo $image->getImagePath(); ?>"/>
                                <div class="carousel-caption">
                                    <p>
                                        <?php echo $image->getDescription(); ?>
                                    </p>
                                </div>
                            </div>
                            <?php $first = false; ?>
                        <?php endforeach; ?>
                    </div>
                    <a class="carousel-control left" href="#pro-slide" data-slide="prev">&lsaquo;</a>
                    <a class="carousel-control right" href="#pro-slide" data-slide="next">&rsaquo;</a>
                </div>
            </div>
            <!-- }}}-->
            <!--Body content-->
        </div>
    </div>
</div>
<script type="text/javascript" charset="utf-8">
    $(function() {
        $('.carousel').carousel();
    });
</script>