<?php
$images = $this->images;
$first = true;
?>


    <ul id="product-slider">

        <?php foreach ($images as $image) : ?>
        <li><img src="<?php echo $image->getImagePath();?>"/></li>
        <?php endforeach; ?>

    </ul>
<!-- }}}-->
<!--Body content-->

<script type="text/javascript" charset="utf-8">
    $(function() {
        $('#product-slider').pikachoose({
            text: { play: "PPP", stop: "SSS", previous: "前进", next: "后退", loading: "Loading" },
            thumbOpacity: 0.1,
            hoverPause: true,
            fadeThumbsIn: true,
            carousel: true,
            carouselOptions: {
                visible: 5,
                wrap: 'circular'
                //visible: 6
            }
        });
    });
</script>