<?php
$this->plugin('formRow')->setTranslator($this->plugin('translate')->getTranslator());
$this->plugin('formRow')->setTranslatorTextDomain('todo');
$title = $this->translate('Add new todo', 'todo');
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('todo', array('action' => 'add')));

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('description'));
echo $this->formRow($form->get('status'));
echo $this->formRow($form->get('assignto'));
echo $this->formRow($form->get('priority'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();

