<h1> <?php echo $this->title;?> </h1>
<table class="table table-striped">
    <tr>
        <th></th>
        <th>Name</th>
        <th>Is primary</th>
        <th></th>
    </tr>
<?php foreach ($this->countries as $country): ?>
    <tr>
        <td></td>
        <td><?php echo $country->getName();?></td>
        <td><?php echo $country->getIsPrimary()? 'yes':'no'?></td>
        <td><a class="btn">edit</a><a class="btn">delete</a></td>
    </tr>
<?php endforeach; ?>
</table>


