<h1> <?php echo $this->title;?> </h1>

<p>
    <a class="btn" href="<?php echo $this->url('country', array('action' => 'add')); ?>">
        Add
    </a>
</p>
<table class="table table-striped">
    <tr>
        <th></th>
        <th>Name</th>
        <th>Is primary</th>
        <th></th>
    </tr>
<?php foreach ($this->countries as $country): ?>
    <tr>
        <td></td>
        <td><?php echo $country->getName();?></td>
        <td><?php echo $country->getIsPrimary()? 'yes':'no'?></td>
        <td><a class="btn" href="<?php echo $this->url(
                'country', array('action' => 'edit', 'id' => $country->getId()));
            ?>">edit</a><a class="btn" href="<?php echo $this->url(
                'country', array('action' => 'delete', 'id' => $country->getId())
            );?>">delete</a></td>
    </tr>
<?php endforeach; ?>
</table>
<?php //echo $this->paginationControl($categories, 'Sliding', 'pagination_control', array('route' => 'country-list'));


