<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('卿作')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
            ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
            ->prependStylesheet($this->basePath() . '/css/front.css')
            ->prependStylesheet($this->basePath() . '/css/style.css')
            ->prependStylesheet($this->basePath() . '/assets/pikachoose-4.5.0/styles/bottom.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/assets/pikachoose-4.5.0/lib/jquery.pikachoose.full.js')
            ->prependFile($this->basePath() . '/assets/pikachoose-4.5.0/lib/jquery.jcarousel.min.js')
            ->prependFile($this->basePath() . '/js/jquery.animate-colors-min.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
        ?>

        <script type="text/javascript" charset="utf-8">
            $(function(){
                $('ul.color-animate-nav li').mouseover(function(event){
                    $(event.target).animate({color: '#808080'}, 400);
                });
                $('ul.color-animate-nav li').mouseout(function(event){
                    $(event.target).animate({color: '#e5e5e5'}, 400);
                });
            });
        </script>
    </head>
    <body>

        <div class="container">
            <div class="container-fluid">
                <div class="content">
                    <div class="row-fluid">

                        <div class="span2">
                            <h2 class="title"><a href="/product/list">卿作</a></h2>
                            <span class="subtitle">Tsingzoo</span>
                            <br/>
                            <br/>
                            <ul class="color-animate-nav">
                                <?php
                                    $cs  = new \Tiddr\Date\ChineseSeason();
                                    foreach (range(0,3) as $number) {
                                        $r = $cs->getLastSeason($number);
                                        $url = $this->url('product-front-filter', array('filter-name' => 'season', 'filter-value' => $r['year'] . '-' . $r['season']));
                                        echo '<li><a href="' . $url . '">' . $r['year'] . " " . $cs->translate($r['season']) . "</a></li>";
                                    }
                                ?>
                                <li><a href="<?php echo $this->url('product-front', array('action' => 'category', 'id' => 7)); ?>">Archived</a></li>
                                <li><a href="#">All</a></li>
                            </ul>
                            <!--Sidebar content-->
                        </div>
                        <div class="span10">
                            <?php echo $this->content; ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="separate-line span12"></div>

            <footer>
                <p>
                    <a href="#">公司简介</a>
                    <a href="#">联系我们</a>
                </p>
                <br/><br/>
                <p>&copy; 2012 by Tsingzoo. <?php echo $this->translate('All rights reserved.') ?> </p>
                <p>Made by<a href="http://tiddr.de">tiddr</a></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
