<!doctype html>
<html>
<head>
    <meta charset="utf-8">
	<title>Tsingzo</title>
    <!-- Scripts -->
    <?php
    echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/assets/pikachoose-4.5.0/lib/jquery.pikachoose.full.js')
        ->prependFile($this->basePath() . '/assets/pikachoose-4.5.0/lib/jquery.jcarousel.min.js')
        ->prependFile($this->basePath() . '/js/jquery.animate-colors-min.js')
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js')
    ?>
	<link rel="stylesheet" type="text/css" href="css/main.css">
</head>
<body>
	<div class="container">
        <?php echo $this->content; ?>
	</div>
</body>
</html>
