<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Tsingzo</title>
    <link rel="stylesheet" type="text/css" href="/css/main.css">
</head>
<body>
<div class="container">
    <div class="header-ext">
        <div class="cate fl">
            <img src="/images/h1.png" witdh="180" height="84" alt="">
        </div>

        <div class="logo fr">
            <a href="/">
                <img src="/images/logo-white.png" width="100" alt="">
            </a>
        </div>
        <div class="search fr">
            <input type="text" class="text">
            <input type="button" class="btn" value="搜索">
        </div>
    </div>
    <div class="product-info">
        <?php echo $this->content; ?>
    </div>
</div>
</body>
</html>
