<?php
$form = $this->form;

$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('description'));
echo $this->formRow($form->get('sequence'));
?>
<img src="<?php echo $this->image->getImagePath(); ?>" />
<?php
echo $this->formRow($form->get('image'));
echo $this->formRow($form->get('submit'));
echo $this->form()->closeTag();
?>