<?php
/**
 * User: wangting
 * Date: 12-11-28
 * Time: 下午12:50
 * copyright 2012 tiddr.de
 */
$title = 'Delete Product';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>Are you sure that you want to delete Person:
    '<?php echo $this->escapeHtml($person->getName()); ?>'?
</p>
<?php
$url = $this->url('person', array(
    'action' => 'delete',
    'id' => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $person->getId(); ?>"/>
        <input type="submit" name="del" value="Yes"/>
        <input type="submit" name="del" value="No"/>
    </div>
</form>
